name: playwright python automation 1 july

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python and Install Dependencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Install Playwright
        run: playwright install
      - name: Run Tests
        run: pytest -n 6 --alluredir=allure-results
      - name: Setup Allure
        run: | 
            sudo apt-get updates
            sudo apt-get install -y unzip wget
            wget https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.zip
            unzip allure-2.27.0.zip
            sudo mv allure-2.27.0/opt/allure
            sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate allure-results -o allure-report --clean